---
name: Sample
description: "Rule which sends an email when an email from vishal.gondil@gmail.com is received"
pack: email
enabled: false
trigger:
  type: email.smtp.message
  parameters: {}
criteria:
  trigger.from:
    pattern: vishal.gondil@gmail.com
    type: contains
action:
  ref: core.sendmail
  parameters:
    body: 'We received an email'
    to: vishal.gondil@gmail.com
    from: vishal.gondil@gmail.com
    subject: 'Email Received'
